FROM ghcr.io/astral-sh/uv:0.1.37 AS uv
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

ENV UV_PYTHON_DOWNLOADS=0

FROM python:3.12-slim AS python

WORKDIR /app

RUN  \
    # we use a cache --mount to reuse the uv cache across builds
    --mount=type=cache,target=/root/.cache/uv \
    # we use a bind --mount to use the uv binary from the uv stage
    --mount=type=bind,from=uv,source=/uv,target=/uv \
    # we use a bind --mount to use the requirements.txt from the host instead of adding a COPY layer
    --mount=type=bind,source=.,target=. \
    /uv sync --locked --no-install-project --no-dev
CMD ["python manage.py runserver 0.0.0.0:8000"]
