FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy UV_SYSTEM_PYTHON=1

ADD . /app
WORKDIR /app
RUN uv sync --locked
RUN find /app
# Install dependencies
#RUN  \
#    --mount=type=cache,target=/root/.cache/uv \
#    --mount=type=bind,source=uv.lock,target=uv.lock \
#    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
#    uv sync --locked --no-install-project --no-dev

# Source code directory needs to be bind mounted in /app during run
# Just run the Podman development kubernetes description
# This should also give an interactive terminal for running other server manage commands
ENTRYPOINT ["uv", "run", "manage.py"]
# Run dev server by default
CMD ["runserver", "0.0.0.0:8000"] 
