# Keeping uv around allows me to not use pip or venvs,
# so let's do that for the dev containerfile
FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim

ENV UV_LINK_MODE=copy UV_SYSTEM_PYTHON=1

# Run as an unprivileged user
RUN useradd -ms /bin/sh -u 1001 app
USER app

WORKDIR /app

# Install dependencies first
COPY --chown=app:app pyproject.toml uv.lock ./
RUN  \
   --mount=type=cache,target=/root/.cache/uv \
   uv sync --locked --no-install-project

# Add rest of app
ADD --chown=app:app . ./

RUN uv sync --locked

# FUTURE: Source code directory needs to be bind mounted in /app during run
# Just run the Podman development kubernetes description
ENTRYPOINT ["uv", "run", "manage.py"]
# Run dev server by default
CMD ["runserver", "0.0.0.0:8000"] 
