# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.6.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/clozeshave-db: 6a566c250e4d94a0a81d19ce117957f22d9515cf23b68496bcffc568de1d8025
    io.kubernetes.cri-o.SandboxID/clozeshave-dev-server: 6a566c250e4d94a0a81d19ce117957f22d9515cf23b68496bcffc568de1d8025
  creationTimestamp: "2025-10-02T02:55:57Z"
  labels:
    app: clozeshave-dev-pod
  name: clozeshave-dev-pod
spec:
  containers:
  - args:
    - postgres
    env:
    - name: POSTGRES_PASSWORD
      value: devtest
    image: docker.io/library/postgres:latest
    name: clozeshave-db
    ports:
    - containerPort: 8000
      hostPort: 10200
    - containerPort: 5432
      hostPort: 10201
    volumeMounts:
    - mountPath: /var/lib/postgresql
      name: 8378ddc73905047a2d15b7c3175828077fb5f2b04ce94d103aaded4baabe1aef-pvc
  - args:
    - runserver
    - 0.0.0.0:8000
    env:
    - name: TERM
      value: xterm
    image: localhost/clozeshave-dev-server:latest
    name: clozeshave-dev-server
    securityContext: {}
    tty: true
  volumes:
  - name: 8378ddc73905047a2d15b7c3175828077fb5f2b04ce94d103aaded4baabe1aef-pvc
    persistentVolumeClaim:
      claimName: 8378ddc73905047a2d15b7c3175828077fb5f2b04ce94d103aaded4baabe1aef
