[tools]
gh = "latest"
rg = "latest"
ruff = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
experimental = true

[tasks.test]
run = "python manage.py test"
[tasks.serve]
run = "python manage.py runserver"