[tools]
gh = "latest"
rg = "latest"
ruff = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = false
experimental = false

[tasks.test]
run = "python manage.py test"
[tasks.serve]
run = "python manage.py runserver"

[env]
_.file='.env'
