[project]
name = "clozeshave"
version = "0.1.0"
description = "Generate cloze-deletion Anki flashcards from unstructured text"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.5",
]
