# Generated by Django 5.2.5 on 2025-09-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_text", models.TextField(verbose_name="OriginalText")),
            ],
            options={
                "verbose_name": "",
                "verbose_name_plural": "s",
            },
        ),
    ]
